import { allPosts, Post } from 'contentlayer/generated'
import PostsList from '../../components/PostsList';

const posts: Post[] = allPosts.sort((a, b) => b.date.localeCompare(a.date));

const totalPost = posts.length;
const postPerPage = 1;
const totalPages = Math.ceil(totalPost/postPerPage);


export const metadata = {
  title: 'Lista de todos los post',
  description: 'Decsripcion post - Generated by create next app',
}

const Posts = () => {
  return (
    <div>
      <h1 className='text-center my-4 text-3xl'>Posts</h1>
      <div className="grid gap-4">
        <PostsList posts={posts}></PostsList>
      </div>
    </div>
  )
}

export default Posts